### ISSUE TITLE
Merak Network: node registration didn't fill in the data-path-ip

### ISSUE THREAD

**Issue by cj-chung** [futurewei-cloud/merak#77]
The node registration in the Merak Network didn't fill in the data-path-ip when sending the request to Alcor. 
The swagger-ui shows the data-path-ip is `null` in the node list.

![image](https://user-images.githubusercontent.com/66383484/186232041-559987eb-d326-4659-bbf7-74d7fe97d58d.png)

**Comment by yanmo96** [comment]
It was the image used to test are old. Just upload new image to .77 to test.  
This code have been tested last week, should be fine👍

**Comment by yanmo96** [comment]
The code to add in this functionality was PR #68 .
